version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - ${QDRANT_PORT}:${QDRANT_PORT}
    expose:
      - ${QDRANT_PORT}
    # configs:
    #   - source: qdrant_config
    #     target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - qdrant

networks:
  qdrant:
